INFO     self_developed_refine.conftest:conftest.py:62 [2025-09-05 10:34:04] 用例 test_vps/test_delete.py::TestDeleteUser::test_delete_userlist 开始登录，环境: uat
INFO     self_developed_refine.conftest:conftest.py:100 UAT登录尝试 1/5，MFA验证码: 353103
INFO     self_developed_refine.conftest:conftest.py:124 UAT登录成功（第1次尝试）
INFO     self_developed_refine.commons.variable_manager:variable_manager.py:111 [2025-09-05 10:33] 运行时变量已保存到: D:\pycharm_test\self_developed_refine\VAR\runtime_vars_vps.json
INFO     self_developed_refine.commons.api_base:api_base.py:239 [2025-09-05 10:34:07] DELETE请求: /mascontrol/user | 数据: [7294]
INFO     root:test_delete.py:499 第1个账号（ID: 7294）删除接口调用成功
INFO     self_developed_refine.commons.api_base:api_base.py:239 [2025-09-05 10:34:08] DELETE请求: /mascontrol/user | 数据: [7291]
INFO     root:test_delete.py:499 第2个账号（ID: 7291）删除接口调用成功
INFO     self_developed_refine.commons.api_base:api_base.py:239 [2025-09-05 10:34:10] DELETE请求: /mascontrol/user | 数据: [7296]
INFO     root:test_delete.py:499 第3个账号（ID: 7296）删除接口调用成功
INFO     self_developed_refine.commons.api_base:api_base.py:239 [2025-09-05 10:34:11] DELETE请求: /mascontrol/user | 数据: [7290]
INFO     root:test_delete.py:499 第4个账号（ID: 7290）删除接口调用成功
INFO     self_developed_refine.commons.api_base:api_base.py:239 [2025-09-05 10:34:13] DELETE请求: /mascontrol/user | 数据: [7293]
INFO     root:test_delete.py:499 第5个账号（ID: 7293）删除接口调用成功
INFO     self_developed_refine.commons.api_base:api_base.py:239 [2025-09-05 10:34:15] DELETE请求: /mascontrol/user | 数据: [7295]
INFO     root:test_delete.py:499 第6个账号（ID: 7295）删除接口调用成功
INFO     self_developed_refine.commons.api_base:api_base.py:239 [2025-09-05 10:34:16] DELETE请求: /mascontrol/user | 数据: [7292]
INFO     root:test_delete.py:499 第7个账号（ID: 7292）删除接口调用成功
INFO     self_developed_refine.conftest:conftest.py:157 [2025-09-05 10:34:17] 用例 test_vps/test_delete.py::TestDeleteUser::test_delete_userlist 执行完毕