INFO     self_developed_refine.conftest:conftest.py:62 [2025-09-04 15:00:28] 用例 test_cloudTrader/test_delete.py::TestDelete_cloudTrader::test_user_belowVps 开始登录，环境: uat
INFO     self_developed_refine.conftest:conftest.py:100 UAT登录尝试 1/5，MFA验证码: 509517
ERROR    self_developed_refine.conftest:conftest.py:129 第1次登录失败: 登录失败: MFA验证失败
INFO     self_developed_refine.conftest:conftest.py:100 UAT登录尝试 2/5，MFA验证码: 385403
INFO     self_developed_refine.conftest:conftest.py:124 UAT登录成功（第2次尝试）
INFO     self_developed_refine.commons.variable_manager:variable_manager.py:111 [2025-09-04 15:00] 运行时变量已保存到: D:\pycharm_test\self_developed_refine\VAR\runtime_vars_cloud.json
INFO     self_developed_refine.commons.variable_manager:variable_manager.py:111 [2025-09-04 15:00] 运行时变量已保存到: D:\pycharm_test\self_developed_refine\VAR\runtime_vars_cloud.json
INFO     self_developed_refine.commons.api_base:api_base.py:152 [2025-09-04 15:00:42] POST请求（JSON）: /mascontrol/user/belowVps | 数据: {'traderUserIds': [7201, 7203, 7208, 7199, 7207, 7202, 7205, 7200, 7204], 'vpsId': [57]}
INFO     self_developed_refine.commons.api_base:api_base.py:160 [2025-09-04 15:00:42] 请求后等待 1 秒
INFO     self_developed_refine.conftest:conftest.py:157 [2025-09-04 15:00:43] 用例 test_cloudTrader/test_delete.py::TestDelete_cloudTrader::test_user_belowVps 执行完毕